### ISSUE TITLE
CSS is no longer a valid syntax and will cause console errors

### ISSUE THREAD

**Issue by monicawheeler** [DockYard/stylelint-config-narwin#21]
CSS is not a valid syntax for the configuration. 

Issue in ember-cli-stylelint: https://github.com/billybonks/ember-cli-stylelint/pull/224

Incorrect documentation: https://github.com/billybonks/ember-cli-stylelint#syntax

Syntax options: https://github.com/stylelint/stylelint/blob/e45e0092058ce8b12b55cbf98855de23647f5b0f/docs/user-guide/node-api.md#syntax

Line 56 in the README.md states:
```
stylelint: {
  linterConfig: {
    syntax: 'css'
  }
}
```

**Comment by eshtadc** [comment]
@monicawheeler  So is `css-in-js` now what you would use for parsing plain `css`?

**Comment by monicawheeler** [comment]
@eshtadc - that's a great question. I haven't been able to really dive into the options, however, when I test in another project, `stylelint` does not actually need the configuration to lint properly. Do you think this can be omitted?

**Comment by Ctannerweb** [comment]
Echoing what Monica outlined. But the `linterConfig:` option doesn't seem to be needed anymore. By default stylelint is linting pure CSS based on the narwin stylelint rules.
